//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industria4.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Industria4.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AUTENTICAR {
            get {
                return ResourceManager.GetString("AUTENTICAR", resourceCulture);
            }
        }
        
        internal static string Email_Nome_Utilizador {
            get {
                return ResourceManager.GetString("Email/Nome Utilizador", resourceCulture);
            }
        }
        
        internal static string GRUPOS {
            get {
                return ResourceManager.GetString("GRUPOS", resourceCulture);
            }
        }
        
        internal static string UTILIZADORES {
            get {
                return ResourceManager.GetString("UTILIZADORES", resourceCulture);
            }
        }
        
        internal static string MsgToSend {
            get {
                return ResourceManager.GetString("MsgToSend", resourceCulture);
            }
        }
        
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        internal static string MsgToUser {
            get {
                return ResourceManager.GetString("MsgToUser", resourceCulture);
            }
        }
        
        internal static string MsgToSendGroup {
            get {
                return ResourceManager.GetString("MsgToSendGroup", resourceCulture);
            }
        }
        
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        internal static string Maximo {
            get {
                return ResourceManager.GetString("Maximo", resourceCulture);
            }
        }
        
        internal static string Minimo {
            get {
                return ResourceManager.GetString("Minimo", resourceCulture);
            }
        }
        
        internal static string Sairsessao {
            get {
                return ResourceManager.GetString("Sairsessao", resourceCulture);
            }
        }
        
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        internal static string NumeroFuncionario {
            get {
                return ResourceManager.GetString("NumeroFuncionario", resourceCulture);
            }
        }
        
        internal static string DadosConta {
            get {
                return ResourceManager.GetString("DadosConta", resourceCulture);
            }
        }
        
        internal static string DadosUtilizador {
            get {
                return ResourceManager.GetString("DadosUtilizador", resourceCulture);
            }
        }
        
        internal static string TipoFuncionario {
            get {
                return ResourceManager.GetString("TipoFuncionario", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string AlterarPassword {
            get {
                return ResourceManager.GetString("AlterarPassword", resourceCulture);
            }
        }
        
        internal static string Confirmarpassword {
            get {
                return ResourceManager.GetString("Confirmarpassword", resourceCulture);
            }
        }
        
        internal static string passwordantiga {
            get {
                return ResourceManager.GetString("passwordantiga", resourceCulture);
            }
        }
        
        internal static string bloquearutilizador {
            get {
                return ResourceManager.GetString("bloquearutilizador", resourceCulture);
            }
        }
        
        internal static string Guardarutilizador {
            get {
                return ResourceManager.GetString("Guardarutilizador", resourceCulture);
            }
        }
        
        internal static string CodigoSensor {
            get {
                return ResourceManager.GetString("CodigoSensor", resourceCulture);
            }
        }
        
        internal static string IdModulo {
            get {
                return ResourceManager.GetString("IdModulo", resourceCulture);
            }
        }
        
        internal static string SensorNome {
            get {
                return ResourceManager.GetString("SensorNome", resourceCulture);
            }
        }
        
        internal static string ValorMax {
            get {
                return ResourceManager.GetString("ValorMax", resourceCulture);
            }
        }
        
        internal static string Observacoes {
            get {
                return ResourceManager.GetString("Observacoes", resourceCulture);
            }
        }
        
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        internal static string Tempo {
            get {
                return ResourceManager.GetString("Tempo", resourceCulture);
            }
        }
        
        internal static string Fator {
            get {
                return ResourceManager.GetString("Fator", resourceCulture);
            }
        }
        
        internal static string numPorta {
            get {
                return ResourceManager.GetString("numPorta", resourceCulture);
            }
        }
        
        internal static string IdTipoPorta {
            get {
                return ResourceManager.GetString("IdTipoPorta", resourceCulture);
            }
        }
        
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        internal static string IdGrandeza {
            get {
                return ResourceManager.GetString("IdGrandeza", resourceCulture);
            }
        }
        
        internal static string ISENABLE {
            get {
                return ResourceManager.GetString("ISENABLE", resourceCulture);
            }
        }
        
        internal static string GuardarSensor {
            get {
                return ResourceManager.GetString("GuardarSensor", resourceCulture);
            }
        }
        
        internal static string ModulosAquisicao {
            get {
                return ResourceManager.GetString("ModulosAquisicao", resourceCulture);
            }
        }
        
        internal static string CodigoModulo {
            get {
                return ResourceManager.GetString("CodigoModulo", resourceCulture);
            }
        }
        
        internal static string NomeModulo {
            get {
                return ResourceManager.GetString("NomeModulo", resourceCulture);
            }
        }
        
        internal static string MaquinaModulo {
            get {
                return ResourceManager.GetString("MaquinaModulo", resourceCulture);
            }
        }
        
        internal static string GuardarModulo {
            get {
                return ResourceManager.GetString("GuardarModulo", resourceCulture);
            }
        }
        
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        internal static string Adicionar {
            get {
                return ResourceManager.GetString("Adicionar", resourceCulture);
            }
        }
        
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        internal static string Localizacao {
            get {
                return ResourceManager.GetString("Localizacao", resourceCulture);
            }
        }
        
        internal static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        internal static string CodigoGateway {
            get {
                return ResourceManager.GetString("CodigoGateway", resourceCulture);
            }
        }
        
        internal static string Savefabrica {
            get {
                return ResourceManager.GetString("Savefabrica", resourceCulture);
            }
        }
        
        internal static string ListaMaquinasAssociadas {
            get {
                return ResourceManager.GetString("ListaMaquinasAssociadas", resourceCulture);
            }
        }
        
        internal static string ListaUtilizadoresFabrica {
            get {
                return ResourceManager.GetString("ListaUtilizadoresFabrica", resourceCulture);
            }
        }
        
        internal static string ListaUtilizadoresMaquina {
            get {
                return ResourceManager.GetString("ListaUtilizadoresMaquina", resourceCulture);
            }
        }
        
        internal static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        internal static string Selecioneutilizadorfabrica {
            get {
                return ResourceManager.GetString("Selecioneutilizadorfabrica", resourceCulture);
            }
        }
        
        internal static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        internal static string ANALISEDEDADOS {
            get {
                return ResourceManager.GetString("ANALISEDEDADOS", resourceCulture);
            }
        }
        
        internal static string FABRICA {
            get {
                return ResourceManager.GetString("FABRICA", resourceCulture);
            }
        }
        
        internal static string MAQUINA {
            get {
                return ResourceManager.GetString("MAQUINA", resourceCulture);
            }
        }
        
        internal static string MODULOAQUISICAO {
            get {
                return ResourceManager.GetString("MODULOAQUISICAO", resourceCulture);
            }
        }
        
        internal static string SENSOR {
            get {
                return ResourceManager.GetString("SENSOR", resourceCulture);
            }
        }
        
        internal static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
        
        internal static string LISTAFABRICAS {
            get {
                return ResourceManager.GetString("LISTAFABRICAS", resourceCulture);
            }
        }
        
        internal static string LISTADEMAQUINAS {
            get {
                return ResourceManager.GetString("LISTADEMAQUINAS", resourceCulture);
            }
        }
        
        internal static string LISTADEMODULOS {
            get {
                return ResourceManager.GetString("LISTADEMODULOS", resourceCulture);
            }
        }
        
        internal static string LISTADESENSORES {
            get {
                return ResourceManager.GetString("LISTADESENSORES", resourceCulture);
            }
        }
        
        internal static string LISTADEUTILIZADORES {
            get {
                return ResourceManager.GetString("LISTADEUTILIZADORES", resourceCulture);
            }
        }
    }
}
